In [32]:
import pandas as pd

In [33]:
ipl = pd.read_csv("ipl_dataset.csv")

***--easy level---***

***Task=Display the first 10 rows of the dataset.***

In [34]:
ipl.head(10)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,5/4/2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,6/4/2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,7/4/2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,8/4/2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,8/4/2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
5,6,2017,Hyderabad,9/4/2017,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
6,7,2017,Mumbai,9/4/2017,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
7,8,2017,Indore,10/4/2017,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
8,9,2017,Pune,11/4/2017,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
9,10,2017,Mumbai,12/4/2017,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN

***Task=Display the last 5 rows.***

In [35]:
print(ipl.tail(5))

      id  season       city      date                team1  \
631  632    2016     Raipur  22/05/16     Delhi Daredevils
632  633    2016  Bangalore  24/05/16        Gujarat Lions
633  634    2016      Delhi  25/05/16  Sunrisers Hyderabad
634  635    2016      Delhi  27/05/16        Gujarat Lions
635  636    2016  Bangalore  29/05/16  Sunrisers Hyderabad

                           team2                  toss_winner toss_decision  \
631  Royal Challengers Bangalore  Royal Challengers Bangalore         field
632  Royal Challengers Bangalore  Royal Challengers Bangalore         field
633        Kolkata Knight Riders        Kolkata Knight Riders         field
634          Sunrisers Hyderabad          Sunrisers Hyderabad         field
635  Royal Challengers Bangalore          Sunrisers Hyderabad           bat

     result  dl_applied                       winner  win_by_runs  \
631  normal           0  Royal Challengers Bangalore            0
632  normal           0  Royal Challengers Bangalore            0
633  normal           0          Sunrisers Hyderabad           22
634  normal           0          Sunrisers Hyderabad            0
635  normal           0          Sunrisers Hyderabad            8

     win_by_wickets player_of_match  \
631               6         V Kohli
632               4  AB de Villiers
633               0    MC Henriques
634               4       DA Warner
635               0     BCJ Cutting

                                                venue          umpire1  \
631  Shaheed Veer Narayan Singh International Stadium   A Nand Kishore
632                             M Chinnaswamy Stadium     AK Chaudhary
633                                  Feroz Shah Kotla        M Erasmus
634                                  Feroz Shah Kotla        M Erasmus
635                             M Chinnaswamy Stadium  HDPK Dharmasena

             umpire2  umpire3
631     BNJ Oxenford      NaN
632  HDPK Dharmasena      NaN
633    C Shamshuddin      NaN
634        CK Nandan      NaN
635     BNJ Oxenford      NaN

***Task=Find the shape of the dataset.***

In [36]:
print(ipl.shape)

(636, 18)

***Task=List all column names.***

In [37]:
print(ipl.columns)

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

***Task=Check data types of all columns.***

In [38]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               636 non-null    int64
 1   season           636 non-null    int64
 2   city             629 non-null    object
 3   date             636 non-null    object
 4   team1            636 non-null    object
 5   team2            636 non-null    object
 6   toss_winner      636 non-null    object
 7   toss_decision    636 non-null    object
 8   result           636 non-null    object
 9   dl_applied       636 non-null    int64
 10  winner           633 non-null    object
 11  win_by_runs      636 non-null    int64
 12  win_by_wickets   636 non-null    int64
 13  player_of_match  633 non-null    object
 14  venue            636 non-null    object
 15  umpire1          635 non-null    object
 16  umpire2          635 non-null    object
 17  umpire3          0 non-null      float64
dtypes: float64(1), int64(5), object(12)
memory usage: 89.6+ KB

***Task=Count the total number of matches.***

In [39]:
print(len(ipl))

636

***Task=Find all unique cities.***

In [40]:
ipl['city'].unique()

array(['Hyderabad', 'Pune', 'Rajkot', 'Indore', 'Bangalore', 'Mumbai',
       'Kolkata', 'Delhi', 'Chandigarh', 'Kanpur', 'Jaipur', 'Chennai',
       'Cape Town', 'Port Elizabeth', 'Durban', 'Centurion',
       'East London', 'Johannesburg', 'Kimberley', 'Bloemfontein',
       'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala', 'Kochi',
       'Visakhapatnam', 'Raipur', 'Ranchi', 'Abu Dhabi', 'Sharjah', nan],
      dtype=object)

***Task=Count missing values in each column.***

In [41]:
ipl.isnull().sum()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               3
win_by_runs          0
win_by_wickets       0
player_of_match      3
venue                0
umpire1              1
umpire2              1
umpire3            636
dtype: int64

***Task=Find all unique seasons.***

In [42]:
ipl['season'].unique()

array([2017, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016])

***Task=Find the number of matches played in season 2017.***

In [43]:
ipl[ipl['season']==2017].shape[0]

59

***Task=Display all matches played in Mumbai.***

In [44]:
ipl[ipl['city'] == 'Mumbai']

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
6,7,2017,Mumbai,9/4/2017,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
9,10,2017,Mumbai,12/4/2017,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
15,16,2017,Mumbai,16/04/17,Gujarat Lions,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,6,N Rana,Wankhede Stadium,A Nand Kishore,S Ravi,NaN
23,24,2017,Mumbai,22/04/17,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,14,0,MJ McClenaghan,Wankhede Stadium,A Nand Kishore,S Ravi,NaN
27,28,2017,Mumbai,24/04/17,Rising Pune Supergiant,Mumbai Indians,Mumbai Indians,field,normal,0,Rising Pune Supergiant,3,0,BA Stokes,Wankhede Stadium,A Nand Kishore,S Ravi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,573,2015,Mumbai,19/05/15,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,25,0,KA Pollard,Wankhede Stadium,HDPK Dharmasena,RK Illingworth,NaN
576,577,2016,Mumbai,9/4/2016,Mumbai Indians,Rising Pune Supergiants,Mumbai Indians,bat,normal,0,Rising Pune Supergiants,0,9,AM Rahane,Wankhede Stadium,HDPK Dharmasena,CK Nandan,NaN
584,585,2016,Mumbai,16/04/16,Mumbai Indians,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,3,AJ Finch,Wankhede Stadium,HDPK Dharmasena,VK Sharma,NaN
589,590,2016,Mumbai,20/04/16,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,6,RG Sharma,Wankhede Stadium,AK Chaudhary,CK Nandan,NaN
599,600,2016,Mumbai,28/04/16,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,6,RG Sharma,Wankhede Stadium,Nitin Menon,RJ Tucker,NaN

***Task=Find all matches won by Mumbai Indians.***

In [45]:
ipl[ipl['winner'] == 'Mumbai Indians']

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
6,7,2017,Mumbai,9/4/2017,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
9,10,2017,Mumbai,12/4/2017,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
11,12,2017,Bangalore,14/04/17,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,KA Pollard,M Chinnaswamy Stadium,KN Ananthapadmanabhan,AK Chaudhary,NaN
15,16,2017,Mumbai,16/04/17,Gujarat Lions,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,6,N Rana,Wankhede Stadium,A Nand Kishore,S Ravi,NaN
21,22,2017,Indore,20/04/17,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,JC Buttler,Holkar Cricket Stadium,M Erasmus,C Shamshuddin,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,597,2016,Chandigarh,25/04/16,Mumbai Indians,Kings XI Punjab,Kings XI Punjab,field,normal,0,Mumbai Indians,25,0,PA Patel,"Punjab Cricket Association IS Bindra Stadium, ...",Nitin Menon,RJ Tucker,NaN
599,600,2016,Mumbai,28/04/16,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,6,RG Sharma,Wankhede Stadium,Nitin Menon,RJ Tucker,NaN
604,605,2016,Pune,1/5/2016,Rising Pune Supergiants,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,RG Sharma,Maharashtra Cricket Association Stadium,AY Dandekar,RJ Tucker,NaN
616,617,2016,Bangalore,11/5/2016,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,6,KH Pandya,M Chinnaswamy Stadium,AY Dandekar,C Shamshuddin,NaN
622,623,2016,Visakhapatnam,15/05/16,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,80,0,KH Pandya,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Nitin Menon,CK Nandan,NaN

***Task=Find the number of unique teams in team1.***

In [46]:
ipl['team1'].nunique()

14

***Task=Display only season, team1, team2, and winner columns.***

In [47]:
ipl[['season', 'team1', 'team2', 'winner']]

,season,team1,team2,winner
0,2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad
1,2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant
2,2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders
3,2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab
4,2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore
...,...,...,...,...
631,2016,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore
632,2016,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore
633,2016,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad
634,2016,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad
635,2016,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad

***Task=Find the total number of matches where D/L method was applied.***

In [48]:
ipl[ipl['dl_applied'] == 1].shape[0]

16

***---medium level---***

***Task=Find top ten city that hosted the most matches.***

In [49]:
top_ten_cites =ipl['city'].value_counts().head(10)
print(top_ten_cites)

city
Mumbai        85
Bangalore     66
Kolkata       61
Delhi         60
Hyderabad     49
Chennai       48
Chandigarh    46
Jaipur        33
Pune          32
Durban        15
Name: count, dtype: int64

***Task=Find the team that won the most matches.***

In [50]:
most_match_win = ipl['winner'].value_counts()
print(most_match_win.head(1))

winner
Mumbai Indians    92
Name: count, dtype: int64

***Task=Find the top 10 players who won "Player of the Match" most often.***

In [51]:
player_of_the_match=ipl['player_of_match'].value_counts().head(10)
print(player_of_the_match)

player_of_match
CH Gayle          18
YK Pathan         16
DA Warner         15
AB de Villiers    15
RG Sharma         14
SK Raina          14
MS Dhoni          13
G Gambhir         13
AM Rahane         12
MEK Hussey        12
Name: count, dtype: int64

***Task=Find the city that hosted the most matches.***

In [52]:
print(ipl['city'].value_counts().head(1))

city
Mumbai    85
Name: count, dtype: int64

***Task=Find the venue where the most matches were played.***

In [53]:
print(ipl['venue'].value_counts().head(2))

venue
M Chinnaswamy Stadium    66
Eden Gardens             61
Name: count, dtype: int64

***Task=Find how many times each team won the toss***

In [54]:
print(ipl['toss_winner'].value_counts().head(5))

toss_winner
Mumbai Indians                 85
Kolkata Knight Riders          78
Delhi Daredevils               72
Royal Challengers Bangalore    70
Kings XI Punjab                68
Name: count, dtype: int64

***Task=Find how many times teams chose Bat or Field after winning the toss.***

In [55]:
print(ipl['toss_decision'].value_counts().head())

toss_decision
field    363
bat      273
Name: count, dtype: int64

***Task=Find matches won by more than 50 runs.***

In [56]:
matches_win_by_50run = ipl[ipl['win_by_runs']>50]
print(matches_win_by_50run[['season','team1','team2','winner','win_by_runs']].value_counts().head(10))

season  team1                        team2                        winner                       win_by_runs
2008    Kings XI Punjab              Mumbai Indians               Kings XI Punjab              66             1
2015    Chennai Super Kings          Kings XI Punjab              Chennai Super Kings          97             1
2013    Chennai Super Kings          Sunrisers Hyderabad          Chennai Super Kings          77             1
        Mumbai Indians               Chennai Super Kings          Mumbai Indians               60             1
                                     Kolkata Knight Riders        Mumbai Indians               65             1
                                     Royal Challengers Bangalore  Mumbai Indians               58             1
        Rajasthan Royals             Mumbai Indians               Rajasthan Royals             87             1
        Royal Challengers Bangalore  Pune Warriors                Royal Challengers Bangalore  130            1
2014    Chennai Super Kings          Delhi Daredevils             Chennai Super Kings          93             1
        Kings XI Punjab              Sunrisers Hyderabad          Kings XI Punjab              72             1
Name: count, dtype: int64

In [57]:
print(matches_win_by_50run[['season','team1','team2','winner','win_by_runs']].head())

    season                   team1                        team2  \
8     2017        Delhi Daredevils       Rising Pune Supergiant
14    2017        Delhi Daredevils              Kings XI Punjab
26    2017   Kolkata Knight Riders  Royal Challengers Bangalore
32    2017  Rising Pune Supergiant  Royal Challengers Bangalore
43    2017          Mumbai Indians             Delhi Daredevils

                    winner  win_by_runs
8         Delhi Daredevils           97
14        Delhi Daredevils           51
26   Kolkata Knight Riders           82
32  Rising Pune Supergiant           61
43          Mumbai Indians          146

***Task=display all the team who win the match more than fifty runs***

In [58]:
matches_win_by_50run

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
8,9,2017,Pune,11/4/2017,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
14,15,2017,Delhi,15/04/17,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,normal,0,Delhi Daredevils,51,0,CJ Anderson,Feroz Shah Kotla,YC Barde,Nitin Menon,NaN
26,27,2017,Kolkata,23/04/17,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,82,0,NM Coulter-Nile,Eden Gardens,CB Gaffaney,CK Nandan,NaN
32,33,2017,Pune,29/04/17,Rising Pune Supergiant,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Rising Pune Supergiant,61,0,LH Ferguson,Maharashtra Cricket Association Stadium,KN Ananthapadmanabhan,M Erasmus,NaN
43,44,2017,Delhi,6/5/2017,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,146,0,LMP Simmons,Feroz Shah Kotla,Nitin Menon,CK Nandan,NaN
59,60,2008,Bangalore,18/04/08,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,NaN
68,69,2008,Chandigarh,25/04/08,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,normal,0,Kings XI Punjab,66,0,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",Aleem Dar,AM Saheba,NaN
100,101,2008,Jaipur,17/05/08,Rajasthan Royals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Rajasthan Royals,65,0,GC Smith,Sawai Mansingh Stadium,BF Bowden,SL Shastri,NaN
114,115,2008,Mumbai,30/05/08,Rajasthan Royals,Delhi Daredevils,Delhi Daredevils,field,normal,0,Rajasthan Royals,105,0,SR Watson,Wankhede Stadium,BF Bowden,RE Koertzen,NaN
118,119,2009,Cape Town,18/04/09,Royal Challengers Bangalore,Rajasthan Royals,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,75,0,R Dravid,Newlands,BR Doctrove,RB Tiffin,NaN
121,122,2009,Port Elizabeth,20/04/09,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings,bat,normal,0,Chennai Super Kings,92,0,M Muralitharan,St George's Park,BG Jerling,SJA Taufel,NaN
131,132,2009,Port Elizabeth,27/04/09,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,bat,normal,0,Mumbai Indians,92,0,SR Tendulkar,St George's Park,BG Jerling,RB Tiffin,NaN
143,144,2009,East London,4/5/2009,Chennai Super Kings,Deccan Chargers,Chennai Super Kings,bat,normal,0,Chennai Super Kings,78,0,MS Dhoni,Buffalo Park,BR Doctrove,M Erasmus,NaN
144,145,2009,Durban,5/5/2009,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,normal,0,Rajasthan Royals,78,0,GC Smith,Kingsmead,SS Hazare,IL Howell,NaN
154,155,2009,Kimberley,11/5/2009,Deccan Chargers,Rajasthan Royals,Deccan Chargers,bat,normal,0,Deccan Chargers,53,0,DR Smith,De Beers Diamond Oval,GAV Baxter,HDPK Dharmasena,NaN
181,182,2010,Kolkata,16/03/10,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings,bat,normal,0,Chennai Super Kings,55,0,MS Dhoni,Eden Gardens,HDPK Dharmasena,AM Saheba,NaN
182,183,2010,Delhi,17/03/10,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,98,0,SR Tendulkar,Feroz Shah Kotla,BR Doctrove,SK Tarapore,NaN
202,203,2010,Delhi,31/03/10,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,bat,normal,0,Delhi Daredevils,67,0,KD Karthik,Feroz Shah Kotla,HDPK Dharmasena,SJA Taufel,NaN
206,207,2010,Mumbai,3/4/2010,Mumbai Indians,Deccan Chargers,Mumbai Indians,bat,normal,0,Mumbai Indians,63,0,AT Rayudu,Brabourne Stadium,BR Doctrove,S Ravi,NaN
225,226,2010,Bangalore,17/04/10,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Mumbai Indians,57,0,R McLaren,M Chinnaswamy Stadium,HDPK Dharmasena,SJA Taufel,NaN
264,265,2011,Kochi,27/04/11,Deccan Chargers,Kochi Tuskers Kerala,Kochi Tuskers Kerala,field,normal,0,Deccan Chargers,55,0,I Sharma,Nehru Stadium,HDPK Dharmasena,AL Hill,NaN
279,280,2011,Bangalore,6/5/2011,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,0,Royal Challengers Bangalore,85,0,CH Gayle,M Chinnaswamy Stadium,Aleem Dar,RB Tiffin,NaN
284,285,2011,Jaipur,9/5/2011,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,normal,0,Chennai Super Kings,63,0,M Vijay,Sawai Mansingh Stadium,K Hariharan,SJA Taufel,NaN
286,287,2011,Chandigarh,10/5/2011,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,normal,0,Kings XI Punjab,76,0,BA Bhatt,"Punjab Cricket Association Stadium, Mohali",SK Tarapore,RJ Tucker,NaN
295,296,2011,Dharamsala,17/05/11,Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab,bat,normal,0,Kings XI Punjab,111,0,AC Gilchrist,Himachal Pradesh Cricket Association Stadium,Asad Rauf,AM Saheba,NaN
299,300,2011,Dharamsala,21/05/11,Deccan Chargers,Kings XI Punjab,Kings XI Punjab,field,normal,0,Deccan Chargers,82,0,S Dhawan,Himachal Pradesh Cricket Association Stadium,Asad Rauf,AM Saheba,NaN
306,307,2011,Chennai,28/05/11,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings,bat,normal,0,Chennai Super Kings,58,0,M Vijay,"MA Chidambaram Stadium, Chepauk",Asad Rauf,SJA Taufel,NaN
312,313,2012,Visakhapatnam,7/4/2012,Chennai Super Kings,Deccan Chargers,Deccan Chargers,field,normal,0,Chennai Super Kings,74,0,RA Jadeja,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,JD Cloete,HDPK Dharmasena,NaN
325,326,2012,Bangalore,15/04/12,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,bat,normal,0,Rajasthan Royals,59,0,AM Rahane,M Chinnaswamy Stadium,JD Cloete,RJ Tucker,NaN
379,380,2012,Chennai,25/05/12,Chennai Super Kings,Delhi Daredevils,Delhi Daredevils,field,normal,0,Chennai Super Kings,86,0,M Vijay,"MA Chidambaram Stadium, Chepauk",BR Doctrove,SJA Taufel,NaN
402,403,2013,Jaipur,17/04/13,Rajasthan Royals,Mumbai Indians,Rajasthan Royals,bat,normal,0,Rajasthan Royals,87,0,AM Rahane,Sawai Mansingh Stadium,Aleem Dar,C Shamshuddin,NaN
403,404,2013,Delhi,18/04/13,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings,bat,normal,0,Chennai Super Kings,86,0,MEK Hussey,Feroz Shah Kotla,M Erasmus,VA Kulkarni,NaN
410,411,2013,Bangalore,23/04/13,Royal Challengers Bangalore,Pune Warriors,Pune Warriors,field,normal,0,Royal Challengers Bangalore,130,0,CH Gayle,M Chinnaswamy Stadium,Aleem Dar,C Shamshuddin,NaN
416,417,2013,Mumbai,27/04/13,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,normal,0,Mumbai Indians,58,0,DR Smith,Wankhede Stadium,Asad Rauf,S Asnani,NaN
429,430,2013,Mumbai,5/5/2013,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,60,0,MG Johnson,Wankhede Stadium,HDPK Dharmasena,CK Nandan,NaN
433,434,2013,Mumbai,7/5/2013,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,bat,normal,0,Mumbai Indians,65,0,SR Tendulkar,Wankhede Stadium,HDPK Dharmasena,S Ravi,NaN
434,435,2013,Hyderabad,8/5/2013,Chennai Super Kings,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Chennai Super Kings,77,0,SK Raina,"Rajiv Gandhi International Stadium, Uppal",S Das,NJ Llong,NaN
464,465,2014,Abu Dhabi,21/04/14,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings,bat,normal,0,Chennai Super Kings,93,0,SK Raina,Sheikh Zayed Stadium,RK Illingworth,C Shamshuddin,NaN
465,466,2014,Sharjah,22/04/14,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Kings XI Punjab,72,0,GJ Maxwell,Sharjah Cricket Stadium,M Erasmus,S Ravi,NaN
497,498,2014,Ahmedabad,15/05/14,Rajasthan Royals,Delhi Daredevils,Delhi Daredevils,field,normal,0,Rajasthan Royals,62,0,AM Rahane,"Sardar Patel Stadium, Motera",S Ravi,RJ Tucker,NaN
541,542,2015,Chennai,25/04/15,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,normal,0,Chennai Super Kings,97,0,BB McCullum,"MA Chidambaram Stadium, Chepauk",JD Cloete,C Shamshuddin,NaN
556,557,2015,Bangalore,6/5/2015,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,0,Royal Challengers Bangalore,138,0,CH Gayle,M Chinnaswamy Stadium,RK Illingworth,VA Kulkarni,NaN
573,574,2015,Pune,20/05/15,Royal Challengers Bangalore,Rajasthan Royals,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,71,0,AB de Villiers,Maharashtra Cricket Association Stadium,AK Chaudhary,C Shamshuddin,NaN
612,613,2016,Visakhapatnam,8/5/2016,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Sunrisers Hyderabad,85,0,A Nehra,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,S Ravi,C Shamshuddin,NaN
619,620,2016,Bangalore,14/05/16,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,normal,0,Royal Challengers Bangalore,144,0,AB de Villiers,M Chinnaswamy Stadium,AY Dandekar,VK Sharma,NaN
622,623,2016,Visakhapatnam,15/05/16,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,80,0,KH Pandya,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Nitin Menon,CK Nandan,NaN
625,626,2016,Bangalore,18/05/16,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,1,Royal Challengers Bangalore,82,0,V Kohli,M Chinnaswamy Stadium,KN Ananthapadmanabhan,M Erasmus,NaN

***Task=find the team who choose the bat firts and win match more than fifty run***

In [59]:
bat_first_and_won = ipl[
    (ipl['toss_decision'] == 'bat') &
    (ipl['win_by_runs'] > 50)
]

print(bat_first_and_won[['season', 'team1', 'team2', 'toss_winner',
                         'toss_decision', 'winner', 'win_by_runs']].value_counts().head(5))

season  team1                        team2                        toss_winner                  toss_decision  winner                       win_by_runs
2009    Chennai Super Kings          Deccan Chargers              Chennai Super Kings          bat            Chennai Super Kings          78             1
                                     Royal Challengers Bangalore  Chennai Super Kings          bat            Chennai Super Kings          92             1
2015    Royal Challengers Bangalore  Rajasthan Royals             Royal Challengers Bangalore  bat            Royal Challengers Bangalore  71             1
        Chennai Super Kings          Kings XI Punjab              Chennai Super Kings          bat            Chennai Super Kings          97             1
2014    Chennai Super Kings          Delhi Daredevils             Chennai Super Kings          bat            Chennai Super Kings          93             1
Name: count, dtype: int64

***Task=Find matches won by more than 8 wickets.***

In [60]:
matches_win_by_wickets=ipl[ipl['win_by_wickets']>8]
print(matches_win_by_wickets[['season','team1','team2','winner','win_by_wickets']].head(5))

    season             team1                   team2                  winner  \
2     2017     Gujarat Lions   Kolkata Knight Riders   Kolkata Knight Riders
5     2017     Gujarat Lions     Sunrisers Hyderabad     Sunrisers Hyderabad
34    2017  Delhi Daredevils         Kings XI Punjab         Kings XI Punjab
53    2017   Kings XI Punjab  Rising Pune Supergiant  Rising Pune Supergiant
61    2008  Rajasthan Royals        Delhi Daredevils        Delhi Daredevils

    win_by_wickets
2               10
5                9
34              10
53               9
61               9

***Task=find matches won by 5 wickets and win the toss and choose field first***

In [61]:
field_first_and_won=ipl[
    (ipl['toss_decision']=='field')&
    (ipl['win_by_wickets']>5)
]

print(field_first_and_won[['season', 'team1', 'team2', 'toss_winner',
                         'toss_decision', 'winner', 'win_by_wickets']].value_counts().head())

season  team1                        team2                  toss_winner            toss_decision  winner                 win_by_wickets
2016    Kolkata Knight Riders        Mumbai Indians         Mumbai Indians         field          Mumbai Indians         6                 2
        Royal Challengers Bangalore  Mumbai Indians         Mumbai Indians         field          Mumbai Indians         6                 2
2008    Chennai Super Kings          Deccan Chargers        Deccan Chargers        field          Deccan Chargers        7                 1
2015    Chennai Super Kings          Kolkata Knight Riders  Kolkata Knight Riders  field          Kolkata Knight Riders  7                 1
2016    Gujarat Lions                Delhi Daredevils       Delhi Daredevils       field          Delhi Daredevils       8                 1
Name: count, dtype: int64

***Task=Find all matches where toss winner also won the match.***

In [62]:
toss_and_match_winner = ipl[ipl['toss_winner'] == ipl['winner']]

print(
    toss_and_match_winner[
        ['season', 'team1', 'team2', 'toss_winner', 'winner']
    ].head()
)

   season                        team1                   team2  \
1    2017               Mumbai Indians  Rising Pune Supergiant
2    2017                Gujarat Lions   Kolkata Knight Riders
3    2017       Rising Pune Supergiant         Kings XI Punjab
4    2017  Royal Challengers Bangalore        Delhi Daredevils
5    2017                Gujarat Lions     Sunrisers Hyderabad

                   toss_winner                       winner
1       Rising Pune Supergiant       Rising Pune Supergiant
2        Kolkata Knight Riders        Kolkata Knight Riders
3              Kings XI Punjab              Kings XI Punjab
4  Royal Challengers Bangalore  Royal Challengers Bangalore
5          Sunrisers Hyderabad          Sunrisers Hyderabad

***Task=Find all matches where CSK toss winner also won the match.***

In [63]:
csk_won_toss_and_match = ipl[
    (ipl['toss_winner'] == 'Chennai Super Kings') &
    (ipl['winner'] == 'Chennai Super Kings')
]

print(csk_won_toss_and_match[['season', 'team1', 'team2', 'toss_winner', 'winner']
    ].head(5).value_counts()
)

season  team1                team2                        toss_winner          winner
2008    Chennai Super Kings  Kings XI Punjab              Chennai Super Kings  Chennai Super Kings    1
                             Royal Challengers Bangalore  Chennai Super Kings  Chennai Super Kings    1
        Delhi Daredevils     Chennai Super Kings          Chennai Super Kings  Chennai Super Kings    1
2009    Chennai Super Kings  Deccan Chargers              Chennai Super Kings  Chennai Super Kings    1
                             Royal Challengers Bangalore  Chennai Super Kings  Chennai Super Kings    1
Name: count, dtype: int64

***Task=find all matches where toss winner lost the match.***

In [64]:
toss_winner_lost = ipl[
    ipl['toss_winner'] != ipl['winner']
]

print(toss_winner_lost[['season','team1','team2','toss_winner','winner','date']].value_counts().head(5))

season  team1                  team2                toss_winner            winner                 date
2008    Chennai Super Kings    Delhi Daredevils     Chennai Super Kings    Delhi Daredevils       2/5/2008    1
2014    Kings XI Punjab        Chennai Super Kings  Chennai Super Kings    Kings XI Punjab        7/5/2014    1
        Kolkata Knight Riders  Kings XI Punjab      Kings XI Punjab        Kolkata Knight Riders  27/05/14    1
                               Delhi Daredevils     Kolkata Knight Riders  Delhi Daredevils       19/04/14    1
        Kings XI Punjab        Sunrisers Hyderabad  Sunrisers Hyderabad    Kings XI Punjab        22/04/14    1
Name: count, dtype: int64

In [65]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               636 non-null    int64
 1   season           636 non-null    int64
 2   city             629 non-null    object
 3   date             636 non-null    object
 4   team1            636 non-null    object
 5   team2            636 non-null    object
 6   toss_winner      636 non-null    object
 7   toss_decision    636 non-null    object
 8   result           636 non-null    object
 9   dl_applied       636 non-null    int64
 10  winner           633 non-null    object
 11  win_by_runs      636 non-null    int64
 12  win_by_wickets   636 non-null    int64
 13  player_of_match  633 non-null    object
 14  venue            636 non-null    object
 15  umpire1          635 non-null    object
 16  umpire2          635 non-null    object
 17  umpire3          0 non-null      float64
dtypes: float64(1), int64(5), object(12)
memory usage: 89.6+ KB

***Task=Find the number of matches played by each team.***

In [66]:
matches_played = pd.concat([ipl['team1'], ipl['team2']]).value_counts().reset_index()

matches_played.columns = ['Team', 'Matches_Played']

print(matches_played)

                           Team  Matches_Played
0                Mumbai Indians             157
1   Royal Challengers Bangalore             152
2         Kolkata Knight Riders             148
3               Kings XI Punjab             148
4              Delhi Daredevils             147
5           Chennai Super Kings             131
6              Rajasthan Royals             118
7           Sunrisers Hyderabad              76
8               Deccan Chargers              75
9                 Pune Warriors              46
10                Gujarat Lions              30
11       Rising Pune Supergiant              16
12         Kochi Tuskers Kerala              14
13      Rising Pune Supergiants              14

***Task=Find the season with the highest number of matches.***

In [67]:
print(ipl['season'].value_counts().head(1))

season
2013    76
Name: count, dtype: int64

In [68]:
season_matches = ipl['season'].value_counts()

print(f"Season: {season_matches.idxmax()}")
print(f"Matches: {season_matches.max()}")

Season: 2013
Matches: 76

***Task=Find the player with the highest Player of the Match awards in a single season.***

In [69]:
player=ipl['player_of_match'].value_counts().idxmax()
awards=ipl['player_of_match'].value_counts().max()

print(f"player: {player}")
print(f"awards: {awards}")

player: CH Gayle
awards: 18

***Task=Find the top 5 venues with most matches.***

In [70]:
top_5_venues=ipl['venue'].value_counts().head(5).reset_index()
top_5_venues.columns=['venue','match']
print(top_5_venues)

                                       venue  match
0                      M Chinnaswamy Stadium     66
1                               Eden Gardens     61
2                           Feroz Shah Kotla     60
3                           Wankhede Stadium     57
4  Rajiv Gandhi International Stadium, Uppal     49

***-----hard level-----***

***Task=Find the win percentage of each team.***

In [71]:
matches_played = pd.concat(
    [ipl['team1'], ipl['team2']]
).value_counts()

matches_won = ipl['winner'].value_counts()

win_percentage = pd.DataFrame({
    'Matches_Played': matches_played,
    'Matches_Won': matches_won
})

win_percentage['Win_Percentage'] = ((
    win_percentage['Matches_Won']
    / win_percentage['Matches_Played']
) * 100).astype(int)

win_percentage = win_percentage.sort_values(
    by='Matches_Played',
    ascending=False
)

print(win_percentage)

                             Matches_Played  Matches_Won  Win_Percentage
Mumbai Indians                          157           92              58
Royal Challengers Bangalore             152           73              48
Kings XI Punjab                         148           70              47
Kolkata Knight Riders                   148           77              52
Delhi Daredevils                        147           62              42
Chennai Super Kings                     131           79              60
Rajasthan Royals                        118           63              53
Sunrisers Hyderabad                      76           42              55
Deccan Chargers                          75           29              38
Pune Warriors                            46           12              26
Gujarat Lions                            30           13              43
Rising Pune Supergiant                   16           10              62
Kochi Tuskers Kerala                     14            6              42
Rising Pune Supergiants                  14            5              35

***Task=Find which team benefited most from winning the toss.***

In [72]:
print(ipl[ipl['toss_winner']==ipl['winner']]['winner'].value_counts().head(1))

winner
Mumbai Indians    48
Name: count, dtype: int64

***Task=Calculate toss-win vs match-win percentage for every team.***

In [73]:
ipl.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,5/4/2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,6/4/2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,7/4/2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,8/4/2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,8/4/2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [74]:
toss_wins = ipl['toss_winner'].value_counts()

toss_match_wins = (
    ipl[ipl['toss_winner'] == ipl['winner']]
    ['winner']
    .value_counts()
)

team_stats = pd.DataFrame({
    'Toss_Wins': toss_wins,
    'Match_Wins_After_Toss': toss_match_wins
})

team_stats['Toss_to_Match_Win_%'] = (
    team_stats['Match_Wins_After_Toss']
    / team_stats['Toss_Wins']
    * 100
).round(2)

team_stats = team_stats.sort_values(
    by='Toss_to_Match_Win_%',
    ascending=False
)

print(team_stats)

                             Toss_Wins  Match_Wins_After_Toss  \
Rising Pune Supergiant               6                      5
Gujarat Lions                       15                     10
Chennai Super Kings                 66                     42
Mumbai Indians                      85                     48
Kolkata Knight Riders               78                     44
Rajasthan Royals                    63                     34
Kochi Tuskers Kerala                 8                      4
Royal Challengers Bangalore         70                     35
Sunrisers Hyderabad                 35                     17
Delhi Daredevils                    72                     33
Deccan Chargers                     43                     19
Rising Pune Supergiants              7                      3
Kings XI Punjab                     68                     28
Pune Warriors                       20                      3

                             Toss_to_Match_Win_%
Rising Pune Supergiant                     83.33
Gujarat Lions                              66.67
Chennai Super Kings                        63.64
Mumbai Indians                             56.47
Kolkata Knight Riders                      56.41
Rajasthan Royals                           53.97
Kochi Tuskers Kerala                       50.00
Royal Challengers Bangalore                50.00
Sunrisers Hyderabad                        48.57
Delhi Daredevils                           45.83
Deccan Chargers                            44.19
Rising Pune Supergiants                    42.86
Kings XI Punjab                            41.18
Pune Warriors                              15.00

***Task=Find the team with the highest average win margin (runs).***

In [75]:
runs_wins=ipl[ipl['win_by_runs']>0]

avg_margin=runs_wins.groupby('winner')['win_by_runs'].mean()
print(avg_margin.sort_values(ascending=False))

winner
Royal Challengers Bangalore    39.866667
Rajasthan Royals               35.695652
Chennai Super Kings            34.500000
Mumbai Indians                 32.595745
Kolkata Knight Riders          28.935484
Delhi Daredevils               27.190476
Kings XI Punjab                26.937500
Rising Pune Supergiants        26.500000
Rising Pune Supergiant         24.600000
Deccan Chargers                23.388889
Pune Warriors                  23.166667
Sunrisers Hyderabad            20.695652
Kochi Tuskers Kerala           11.500000
Gujarat Lions                   1.000000
Name: win_by_runs, dtype: float64

***Task=Find the team with the highest average win margin (wickets).***

In [76]:
wickets_wins=ipl[ipl['win_by_wickets']>0]
avg_margin=wickets_wins.groupby('winner')['win_by_wickets'].mean()
print(avg_margin.sort_values(ascending=False).astype(int))

winner
Kochi Tuskers Kerala           7
Rising Pune Supergiants        6
Royal Challengers Bangalore    6
Deccan Chargers                6
Delhi Daredevils               6
Sunrisers Hyderabad            6
Kolkata Knight Riders          6
Kings XI Punjab                6
Chennai Super Kings            6
Rising Pune Supergiant         6
Mumbai Indians                 6
Rajasthan Royals               6
Pune Warriors                  6
Gujarat Lions                  5
Name: win_by_wickets, dtype: int64

***Task=Create a pivot table showing teams as rows and seasons as columns with number of wins.***

In [77]:
pivot_table=pd.pivot_table(
    ipl,
    index='winner',
    columns='season',
    values='id',
    aggfunc='count',
    fill_value=0
)
print(pivot_table)

season                       2008  2009  2010  2011  2012  2013  2014  2015  \
winner
Chennai Super Kings             9     8     9    11    10    12    10    10
Deccan Chargers                 2     9     8     6     4     0     0     0
Delhi Daredevils                7    10     7     4    11     3     2     5
Gujarat Lions                   0     0     0     0     0     0     0     0
Kings XI Punjab                10     7     4     7     8     8    12     3
Kochi Tuskers Kerala            0     0     0     6     0     0     0     0
Kolkata Knight Riders           6     3     7     8    12     6    11     7
Mumbai Indians                  7     5    11    10    10    13     7    10
Pune Warriors                   0     0     0     4     4     4     0     0
Rajasthan Royals               13     6     6     6     7    11     7     7
Rising Pune Supergiant          0     0     0     0     0     0     0     0
Rising Pune Supergiants         0     0     0     0     0     0     0     0
Royal Challengers Bangalore     4     9     8    10     8     9     5     8
Sunrisers Hyderabad             0     0     0     0     0    10     6     7

season                       2016  2017
winner
Chennai Super Kings             0     0
Deccan Chargers                 0     0
Delhi Daredevils                7     6
Gujarat Lions                   9     4
Kings XI Punjab                 4     7
Kochi Tuskers Kerala            0     0
Kolkata Knight Riders           8     9
Mumbai Indians                  7    12
Pune Warriors                   0     0
Rajasthan Royals                0     0
Rising Pune Supergiant          0    10
Rising Pune Supergiants         5     0
Royal Challengers Bangalore     9     3
Sunrisers Hyderabad            11     8